services:
  - type: web
    name: music-app-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
  - type: web
    name: music-app-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./dist"
    routes:
      - type: rewrite
        source: /api/*
        destination: https://harmonyvibe.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
